[package]
name = "mushi-python"
version = "0.0.0"
edition = "2024"

[lib]
name = "mushi"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
mushi = { version = "0.0.12", path = "../lib" }
thiserror = "2.0.12"
